export type Locale = "en" | "es";

const es: Record<string, string> = {
  "nav.journals": "Revistas",
  "nav.articles": "Artículos",
  "nav.editorial": "Editorial",
  "nav.researchers": "Investigadores",
  "nav.datasets": "Datos",
  "nav.protocols": "Protocolos",
  "nav.search": "Buscar",
  "nav.signin": "Iniciar sesión",
  "nav.submit": "Enviar manuscrito",
  "nav.dashboard": "Panel",
  "nav.logout": "Cerrar sesión",
  "nav.menu": "Menú",
  "search.placeholder": "Buscar artículos, autores, revistas…",
  "search.button": "Buscar",
  "search.title": "Buscar en la revista",
  "search.empty.title": "Escribe una consulta para empezar",
  "search.empty.body": "Busca artículos, investigadores, revistas, datasets y protocolos.",
  "search.no_results_for": "Sin resultados para",
  "search.try_different": "Prueba otra palabra clave o revisa la ortografía.",
  "search.results_for": "Resultados para",
  "search.no_results": "Sin resultados. Intenta con otros términos.",
  "search.advanced": "Búsqueda avanzada",
  "search.advanced.hint":
    "Combina campos con operadores lógicos: AND exige que todos los términos coincidan; OR devuelve elementos que coincidan con cualquiera.",
  "search.field.keywords": "Título / palabras clave",
  "search.field.author": "Nombre de autor",
  "search.field.journal": "Revista",
  "search.field.type": "Tipo de artículo",
  "search.field.type.any": "Cualquier tipo",
  "search.field.type.research_article": "Artículo de investigación",
  "search.field.type.review_article": "Revisión",
  "search.field.type.short_communication": "Comunicación breve",
  "search.field.type.methods_article": "Artículo de métodos",
  "search.field.type.data_paper": "Artículo de datos",
  "search.field.type.perspective": "Perspectiva",
  "search.field.type.commentary": "Comentario",
  "search.field.type.correspondence": "Correspondencia",
  "search.field.scope": "Contenido",
  "search.field.scope.all": "Todo el contenido",
  "search.field.scope.article": "Artículos",
  "search.field.scope.researcher": "Investigadores",
  "search.field.scope.journal": "Revistas",
  "search.field.scope.dataset": "Datasets",
  "search.field.scope.protocol": "Protocolos",
  "search.op.and": "Todos los términos (AND)",
  "search.op.or": "Cualquier término (OR)",
  "search.advanced.run": "Ejecutar búsqueda avanzada",
  "search.advanced.clear": "Limpiar campos",
  "search.advanced.results": "resultados",
  "search.advanced.empty": "Ajusta los campos y ejecuta la búsqueda para ver resultados.",
  "search.type.article": "Artículo",
  "search.type.researcher": "Investigador",
  "search.type.journal": "Revista",
  "search.type.dataset": "Dataset",
  "search.type.protocol": "Protocolo",
  "journal.issn": "ISSN",
  "journal.open_access": "Acceso abierto",
  "journal.articles_count": "artículos",
  "journal.info": "Información de la revista",
  "journal.sections": "Secciones",
  "journal.special_issues": "Números especiales",
  "journal.editorial_board": "Comité editorial",
  "journal.deadline": "plazo",
  "journal.more_articles": "Más artículos…",
  "journal.submit_to": "Enviar a {name}",
  "journal.review_for": "Revisar para {name}",
  "journal.share": "Compartir",
  "journal.menu": "Menú de la revista",
  "journal.menu.home": "Inicio",
  "journal.menu.aims": "Objetivos y alcance",
  "journal.menu.board": "Comité editorial",
  "journal.menu.instructions": "Instrucciones para autores",
  "journal.highly_accessed": "Artículos más visitados",
  "journal.credentials.title": "Información de la revista",
  "journal.cred.open_access": "Acceso abierto: lectura gratuita para todos; los cargos de procesamiento se cubren mediante el ecosistema de publicación.",
  "journal.cred.high_visibility": "Alta visibilidad: los artículos se distribuyen abiertamente en la Web con DOI persistentes.",
  "journal.cred.rigorous": "Revisión rigurosa: flujo editorial transparente con estado verificable de cada manuscrito.",
  "journal.cred.data": "Datos abiertos: conjuntos de datos y protocolos publicados bajo licencias abiertas.",
  "journal.metrics.articles": "Artículos",
  "journal.metrics.views": "Visitas totales",
  "journal.metrics.citations": "Citas",
  "journal.alert.title": "Alerta por correo",
  "journal.alert.body": "Recibe los artículos más recientes directamente en tu bandeja de entrada.",
  "journal.alert.subscribe": "Suscribirse",
  "journal.alert.done": "¡Suscrito! Revisa tu correo.",
  "journal.news.title": "Noticias",
  "journal.news.more": "Más datasets",
  "article.open_access_badge": "Acceso abierto",
  "article.belongs_section": "Este artículo pertenece a la Sección {section}.",
  "searchrow.label": "Buscar artículos:",
  "searchrow.title_keyword": "Título / Palabra clave",
  "searchrow.author_affiliation": "Autor / Afiliación / Email",
  "searchrow.all_journals": "Todas las revistas",
  "searchrow.all_types": "Todos los tipos",
  "searchrow.advanced": "Avanzada",
  "footer.eissn": "eISSN",
  "footer.published_by": "Publicado por",
  "footer.rss": "RSS",
  "footer.content_alert": "Alerta de contenido",
  "footer.newsletter.title": "Mantente al día",
  "footer.newsletter.body": "Suscríbete al boletín para recibir la investigación caribeña más reciente.",
  "footer.newsletter.subscribe": "Suscribirse",
  "footer.newsletter.placeholder": "Tu correo",
  "footer.newsletter.done": "¡Suscrito, gracias!",
  "footer.further.title": "Más información",
  "footer.further.editorial": "Acerca del editor",
  "footer.further.apc": "Cargos por procesamiento",
  "footer.further.oa_policy": "Política de acceso abierto",
  "footer.further.contact": "Contacto",
  "footer.further.libraries": "Para bibliotecas",
  "footer.guides.title": "Guías",
  "footer.guides.authors": "Para autores",
  "footer.guides.reviewers": "Para revisores",
  "footer.guides.editors": "Para editores",
  "footer.guides.societies": "Para sociedades",
  "footer.guides.institutions": "Para instituciones",
  "footer.initiatives.title": "Iniciativas CARIBE",
  "footer.involved.title": "Participa",
  "footer.involved.submit": "Envía un manuscrito",
  "footer.involved.review": "Revisa artículos",
  "footer.involved.dataset": "Propón un dataset",
  "footer.involved.register": "Únete al registro",
  "footer.legal.disclaimer": "Aviso legal",
  "footer.legal.notice": "Aviso legal",
  "footer.legal.terms": "Términos y condiciones",
  "footer.legal.privacy": "Política de privacidad",
  "footer.legal.accessibility": "Accesibilidad",
  "legal.privacy.title": "Política de privacidad",
  "legal.privacy.p1": "CARIBE SCIENCE recopila únicamente la información necesaria para operar la plataforma: datos de cuenta (nombre, correo, institución) y estadísticas de uso agregadas. Nunca vendemos ni compartimos datos personales con terceros.",
  "legal.privacy.p2": "Las cuentas demo del entorno local no almacenan datos personales reales. El acceso a manuscritos y datos está protegido por roles y autenticación con token.",
  "legal.privacy.p3": "Puedes solicitar la eliminación de tu cuenta y sus datos escribiendo al comité editorial. Conservamos únicamente lo exigido por la normativa vigente.",
  "legal.terms.title": "Términos y condiciones",
  "legal.terms.p1": "Al usar CARIBE SCIENCE aceptas publicar contenido original y de tu autoría, respetar los procesos editoriales y no manipular métricas, DOIs ni índices.",
  "legal.terms.p2": "El contenido editorial se licencia bajo CC BY 4.0 salvo indicación contraria. Los datos y protocolos conservan la licencia declarada por sus autores.",
  "legal.terms.p3": "La plataforma se ofrece sin garantías de disponibilidad continua; el acceso a los servicios requiere credenciales válidas y el uso conforme a las guías de autor.",
  "legal.access.title": "Accesibilidad",
  "legal.access.p1": "CARIBE SCIENCE está diseñado para ser utilizable por teclado, con contraste AA en los textos, jerarquía semántica de encabezados y etiquetas descriptivas en formularios.",
  "legal.access.p2": "Las etiquetas y roles ARIA guían a los lectores de pantalla en la navegación; los elementos interactivos principales tienen alternativas textuales.",
  "legal.access.p3": "Si encuentras una barrera de accesibilidad, escríbenos y la corregiremos. El soporte de temas oscuros y tipografías legibles se mantiene como parte del diseño base.",
  "article.published_in": "Publicado en",
  "article.authors_label": "Autores",
  "footer.tagline": "Avanzando el conocimiento científico desde el Caribe hacia el mundo.",
  "footer.about": "Acerca de",
  "footer.integrity": "Integridad científica",
  "footer.guidelines": "Guías para autores",
  "footer.contact": "Contacto",
  "footer.rights": "Contenido editorial bajo licencia",
  "footer.by": "Hecho con rigor científico en el Caribe.",
  "common.loading": "Cargando…",
  "common.error": "Algo salió mal",
  "common.back": "Volver",
  "common.view_all": "Ver todo",
  "common.published": "Publicado",
  "common.views": "visitas",
  "common.downloads": "descargas",
  "common.citations": "citas",
  "common.open_access": "Acceso abierto",
  "common.read_more": "Leer más",
  "common.submit": "Enviar",
  "auth.welcome": "Bienvenido de nuevo",
  "auth.subtitle": "Accede a tu panel de investigación.",
  "auth.email": "Correo electrónico",
  "auth.password": "Contraseña",
  "auth.login": "Iniciar sesión",
  "auth.register": "Crear cuenta",
  "auth.no_account": "¿No tienes cuenta?",
  "auth.have_account": "¿Ya tienes cuenta?",
  "auth.full_name": "Nombre completo",
  "auth.create_account": "Crear cuenta",
  "auth.demo_hint": "Cuentas demo: admin@example.com / Admin123!",
  "home.hero_kicker": "Publicación científica del Caribe",
  "home.hero_title": "Del Caribe para el mundo.",
  "home.hero_subtitle":
    "Una plataforma editorial abierta y rigurosa que impulsa la investigación de la región: revisión por pares transparente, datos abiertos y acceso libre para todos.",
  "home.hero_cta_submit": "Enviar un manuscrito",
  "home.hero_cta_read": "Explorar artículos",
  "home.mission.title": "Nuestra misión",
  "home.mission.body":
    "Cerrar la brecha entre la producción científica del Caribe y su visibilidad global, con procesos editoriales íntegros y tecnología moderna.",
  "home.stats.articles": "Artículos publicados",
  "home.stats.researchers": "Investigadores",
  "home.stats.institutions": "Instituciones",
  "home.stats.journals": "Revistas",
  "home.stats.datasets": "Datasets",
  "home.stats.countries": "Países",
  "home.stats.views": "Visitas",
  "home.journals.title": "Revistas",
  "home.journals.subtitle": "Publicaciones lideradas por la comunidad científica de la región.",
  "home.latest.title": "Artículos recientes",
  "home.latest.subtitle": "La investigación más reciente de la región, con acceso abierto.",
  "home.researchers.title": "Investigadores destacados",
  "home.researchers.subtitle": "Conoce a quienes construyen el conocimiento del Caribe.",
  "home.datasets.title": "Datos abiertos",
  "home.datasets.body":
    "Los artículos publicados están respaldados por datasets y protocolos accesibles bajo licencias abiertas.",
  "home.caribbean.title": "El Caribe en el mapa",
  "home.caribbean.body":
    "Una red de talento que se extiende por todas las islas y costas de la cuenca caribeña: países, instituciones y comunidades científicas conectadas.",
  "home.integrity.title": "Integridad sobre todo",
  "home.integrity.body":
    "Nunca fabricamos métricas, DOIs ni índices. Cada dato mostrado refleja el estado real y verificado de nuestro sistema editorial.",
  "home.cta.title": "¿Listo para publicar?",
  "home.cta.body":
    "Envía tu manuscrito y sé parte de la comunidad científica del Caribe.",
  "main.hero_title": "El Caribe en la ciencia",
  "workflow.draft": "Borrador",
  "workflow.submitted": "Enviado",
  "workflow.technical_check": "Revisión técnica",
  "workflow.editorial_check": "Revisión editorial",
  "workflow.assigned_to_editor": "Asignado a editor",
  "workflow.reviewer_invitations": "Invitando revisores",
  "workflow.under_review": "En revisión",
  "workflow.reviews_received": "Revisiones recibidas",
  "workflow.editor_decision": "Decisión editorial",
  "workflow.rejected": "Rechazado",
  "workflow.minor_revision": "Revisión menor",
  "workflow.major_revision": "Revisión mayor",
  "workflow.accepted": "Aceptado",
  "workflow.production": "En producción",
  "workflow.proof": "En pruebas",
  "workflow.published": "Publicado",
};

const en: Record<string, string> = {
  "nav.journals": "Journals",
  "nav.articles": "Articles",
  "nav.editorial": "Editorial",
  "nav.researchers": "Researchers",
  "nav.datasets": "Datasets",
  "nav.protocols": "Protocols",
  "nav.search": "Search",
  "nav.signin": "Sign in",
  "nav.submit": "Submit a manuscript",
  "nav.dashboard": "Dashboard",
  "nav.logout": "Log out",
  "nav.menu": "Menu",
  "search.placeholder": "Search articles, authors, journals…",
  "search.button": "Search",
  "search.title": "Search the journal",
  "search.empty.title": "Type a query to start searching",
  "search.empty.body": "Search articles, researchers, journals, datasets and protocols.",
  "search.no_results_for": "No results for",
  "search.try_different": "Try a different keyword, or check the spelling.",
  "search.results_for": "Results for",
  "search.no_results": "No results. Try different terms.",
  "search.advanced": "Advanced search",
  "search.advanced.hint":
    "Combine fields with logical operators: AND requires all terms to match; OR returns items matching any of them.",
  "search.field.keywords": "Title / keywords",
  "search.field.author": "Author name",
  "search.field.journal": "Journal",
  "search.field.type": "Article type",
  "search.field.type.any": "Any type",
  "search.field.type.research_article": "Research article",
  "search.field.type.review_article": "Review",
  "search.field.type.short_communication": "Short communication",
  "search.field.type.methods_article": "Methods article",
  "search.field.type.data_paper": "Data paper",
  "search.field.type.perspective": "Perspective",
  "search.field.type.commentary": "Commentary",
  "search.field.type.correspondence": "Correspondence",
  "search.field.scope": "Content",
  "search.field.scope.all": "All content",
  "search.field.scope.article": "Articles",
  "search.field.scope.researcher": "Researchers",
  "search.field.scope.journal": "Journals",
  "search.field.scope.dataset": "Datasets",
  "search.field.scope.protocol": "Protocols",
  "search.op.and": "All terms (AND)",
  "search.op.or": "Any term (OR)",
  "search.advanced.run": "Run advanced search",
  "search.advanced.clear": "Clear fields",
  "search.advanced.results": "results",
  "search.advanced.empty": "Adjust the fields and run the search to see results.",
  "search.type.article": "Article",
  "search.type.researcher": "Researcher",
  "search.type.journal": "Journal",
  "search.type.dataset": "Dataset",
  "search.type.protocol": "Protocol",
  "journal.issn": "ISSN",
  "journal.open_access": "Open access",
  "journal.articles_count": "articles",
  "journal.info": "Journal info",
  "journal.sections": "Sections",
  "journal.special_issues": "Special issues",
  "journal.editorial_board": "Editorial board",
  "journal.deadline": "deadline",
  "journal.more_articles": "More articles…",
  "journal.submit_to": "Submit to {name}",
  "journal.review_for": "Review for {name}",
  "journal.share": "Share",
  "journal.menu": "Journal menu",
  "journal.menu.home": "Home",
  "journal.menu.aims": "Aims & Scope",
  "journal.menu.board": "Editorial board",
  "journal.menu.instructions": "Instructions for authors",
  "journal.highly_accessed": "Highly accessed articles",
  "journal.credentials.title": "Journal information",
  "journal.cred.open_access": "Open Access: free for readers worldwide; processing charges are covered through the publishing ecosystem.",
  "journal.cred.high_visibility": "High visibility: articles are openly distributed across the Web with persistent DOIs.",
  "journal.cred.rigorous": "Rigorous review: transparent editorial workflow with a verifiable status for every manuscript.",
  "journal.cred.data": "Open data: datasets and protocols are published under open licenses.",
  "journal.metrics.articles": "Articles",
  "journal.metrics.views": "Total views",
  "journal.metrics.citations": "Citations",
  "journal.alert.title": "E-Mail Alert",
  "journal.alert.body": "Receive the latest articles directly in your inbox.",
  "journal.alert.subscribe": "Subscribe",
  "journal.alert.done": "Subscribed — check your inbox.",
  "journal.news.title": "News",
  "journal.news.more": "More datasets",
  "article.open_access_badge": "Open access",
  "article.belongs_section": "This article belongs to the Section {section}.",
  "searchrow.label": "Search for Articles:",
  "searchrow.title_keyword": "Title / Keyword",
  "searchrow.author_affiliation": "Author / Affiliation / Email",
  "searchrow.all_journals": "All journals",
  "searchrow.all_types": "All article types",
  "searchrow.advanced": "Advanced",
  "footer.eissn": "eISSN",
  "footer.published_by": "Published by",
  "footer.rss": "RSS",
  "footer.content_alert": "Content alert",
  "footer.newsletter.title": "Stay updated",
  "footer.newsletter.body": "Subscribe to the newsletter for the latest Caribbean research.",
  "footer.newsletter.subscribe": "Sign up",
  "footer.newsletter.placeholder": "Your email",
  "footer.newsletter.done": "Subscribed — thank you!",
  "footer.further.title": "Further information",
  "footer.further.editorial": "About the Editor",
  "footer.further.apc": "Article processing charges",
  "footer.further.oa_policy": "Open access policy",
  "footer.further.contact": "Contact",
  "footer.further.libraries": "For libraries",
  "footer.guides.title": "Guidelines",
  "footer.guides.authors": "For authors",
  "footer.guides.reviewers": "For reviewers",
  "footer.guides.editors": "For editors",
  "footer.guides.societies": "For societies",
  "footer.guides.institutions": "For institutions",
  "footer.initiatives.title": "CARIBE initiatives",
  "footer.involved.title": "Get involved",
  "footer.involved.submit": "Submit a manuscript",
  "footer.involved.review": "Review articles",
  "footer.involved.dataset": "Propose a dataset",
  "footer.involved.register": "Join the registry",
  "footer.legal.disclaimer": "Disclaimer",
  "footer.legal.notice": "Legal notice",
  "footer.legal.terms": "Terms and conditions",
  "footer.legal.privacy": "Privacy policy",
  "footer.legal.accessibility": "Accessibility",
  "legal.privacy.title": "Privacy Policy",
  "legal.privacy.p1": "CARIBE SCIENCE collects only the information needed to operate the platform: account data (name, email, institution) and aggregate usage statistics. We never sell or share personal data with third parties.",
  "legal.privacy.p2": "Demo accounts in the local environment store no real personal data. Access to manuscripts and data is protected by roles and token-based authentication.",
  "legal.privacy.p3": "You may request deletion of your account and its data by writing to the editorial committee. We retain only what is required by current regulations.",
  "legal.terms.title": "Terms and Conditions",
  "legal.terms.p1": "By using CARIBE SCIENCE you agree to publish original content of your own authorship, respect editorial processes, and never manipulate metrics, DOIs, or indexes.",
  "legal.terms.p2": "Editorial content is licensed under CC BY 4.0 unless stated otherwise. Datasets and protocols keep the license declared by their authors.",
  "legal.terms.p3": "The platform is provided without guarantees of continuous availability; access requires valid credentials and use consistent with the author guidelines.",
  "legal.access.title": "Accessibility",
  "legal.access.p1": "CARIBE SCIENCE is designed to be fully keyboard-usable, with AA contrast for text, semantic heading hierarchy, and descriptive form labels.",
  "legal.access.p2": "ARIA labels and roles guide screen readers through the navigation; primary interactive elements have textual alternatives.",
  "legal.access.p3": "If you find an accessibility barrier, write to us and we will fix it. Dark theme support and legible typography are part of the base design.",
  "article.published_in": "Published in",
  "article.authors_label": "Authors",
  "footer.tagline": "Advancing scientific knowledge from the Caribbean to the world.",
  "footer.about": "About",
  "footer.integrity": "Scientific integrity",
  "footer.guidelines": "Author guidelines",
  "footer.contact": "Contact",
  "footer.rights": "Editorial content licensed under",
  "footer.by": "Built with scientific rigor in the Caribbean.",
  "common.loading": "Loading…",
  "common.error": "Something went wrong",
  "common.back": "Back",
  "common.view_all": "View all",
  "common.published": "Published",
  "common.views": "views",
  "common.downloads": "downloads",
  "common.citations": "citations",
  "common.open_access": "Open access",
  "common.read_more": "Read more",
  "common.submit": "Submit",
  "auth.welcome": "Welcome back",
  "auth.subtitle": "Access your research dashboard.",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.login": "Sign in",
  "auth.register": "Create account",
  "auth.no_account": "Don't have an account?",
  "auth.have_account": "Already have an account?",
  "auth.full_name": "Full name",
  "auth.create_account": "Create account",
  "auth.demo_hint": "Demo accounts: admin@example.com / Admin123!",
  "home.hero_kicker": "Caribbean scientific publishing",
  "home.hero_title": "From the Caribbean to the world.",
  "home.hero_subtitle":
    "An open, rigorous publishing platform powering the region's research: transparent peer review, open data, and free access for everyone.",
  "home.hero_cta_submit": "Submit a manuscript",
  "home.hero_cta_read": "Explore articles",
  "home.mission.title": "Our mission",
  "home.mission.body":
    "Close the gap between the Caribbean's scientific output and its global visibility through rigorous editorial processes and modern technology.",
  "home.stats.articles": "Published articles",
  "home.stats.researchers": "Researchers",
  "home.stats.institutions": "Institutions",
  "home.stats.journals": "Journals",
  "home.stats.datasets": "Datasets",
  "home.stats.countries": "Countries",
  "home.stats.views": "Views",
  "home.journals.title": "Journals",
  "home.journals.subtitle": "Publications led by the region's scientific community.",
  "home.latest.title": "Latest articles",
  "home.latest.subtitle": "The region's newest research, open access.",
  "home.researchers.title": "Featured researchers",
  "home.researchers.subtitle": "Meet the people building Caribbean knowledge.",
  "home.datasets.title": "Open data",
  "home.datasets.body":
    "Published articles are backed by datasets and protocols available under open licenses.",
  "home.caribbean.title": "The Caribbean on the map",
  "home.caribbean.body":
    "A network of talent spanning every island and coast of the Caribbean basin: countries, institutions, and scientific communities connected.",
  "home.integrity.title": "Integrity first",
  "home.integrity.body":
    "We never fabricate metrics, DOIs, or indexes. Every figure shown reflects the real, verified state of our editorial system.",
  "home.cta.title": "Ready to publish?",
  "home.cta.body": "Submit your manuscript and join the Caribbean scientific community.",
  "main.hero_title": "The Caribbean in science",
  "workflow.draft": "Draft",
  "workflow.submitted": "Submitted",
  "workflow.technical_check": "Technical check",
  "workflow.editorial_check": "Editorial check",
  "workflow.assigned_to_editor": "Assigned to editor",
  "workflow.reviewer_invitations": "Inviting reviewers",
  "workflow.under_review": "Under review",
  "workflow.reviews_received": "Reviews received",
  "workflow.editor_decision": "Editor decision",
  "workflow.rejected": "Rejected",
  "workflow.minor_revision": "Minor revision",
  "workflow.major_revision": "Major revision",
  "workflow.accepted": "Accepted",
  "workflow.production": "In production",
  "workflow.proof": "In proofing",
  "workflow.published": "Published",
};

export const dicts: Record<Locale, Record<string, string>> = { en, es };

export function getInitialLocale(): Locale {
  if (typeof window === "undefined") return "en";
  const saved = window.localStorage.getItem("caribe_locale");
  return saved === "es" ? "es" : "en";
}

export function t(locale: Locale, key: string): string {
  return dicts[locale][key] ?? dicts.en[key] ?? key;
}

export async function getServerLocale(): Promise<Locale> {
  try {
    const { cookies } = await import("next/headers");
    const store = await cookies();
    const v = store.get("caribe_locale")?.value;
    return v === "es" ? "es" : "en";
  } catch {
    return "en";
  }
}